name: flutter_core_storage
description: A comprehensive storage service package for Flutter applications with SharedPreferences, Hive database, secure storage, file operations, and cache management.
version: 1.0.0
homepage: https://github.com/Cat1m/flutter_core_storage

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Local storage
  shared_preferences: ^2.2.2
  
  # Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Secure storage
  flutter_secure_storage: ^9.0.0
  
  # File operations
  path_provider: ^2.1.1
  path: ^1.8.3
  
  # Utilities
  equatable: ^2.0.5
  meta: ^1.9.1
  
  # JSON handling
  json_annotation: ^4.8.1
  
  # Encryption
  crypto: ^3.0.3
  encrypt: ^5.0.3
  
  # Logging
  logger: ^2.0.2+1
  convert: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  # Testing
  mocktail: ^1.0.1
  
  # Code generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android package name to use when the 'pluginClass' is defined.
  # This is required when using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  #
  # Please do not manually edit this section, as it is auto-generated.
  
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
